version: '3.9'

services:
  jekyll:
    image: jekyll/jekyll:3
    command: jekyll serve --watch --force_polling --verbose
    ports:
      - 4000:4000
    volumes:
      - ./jekyll:/srv/jekyll:delegated
  ui:
    image: node:alpine
    entrypoint: ""
    command: "/bin/sh -c 'yarn install --immutable && yarn run watch'"
    working_dir: /usr/src/
    environment:
      GULP_DESTINATION_DIR: /dist
    volumes:
      - ./ui:/usr/src:delegated
      - ./jekyll/assets/compiled:/dist:delegated
