version: '3.9'

services:
  jekyll:
    image: jekyll/jekyll:3
    command: jekyll serve --watch --force_polling --verbose
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll:delegated
  ui:
    image: node:alpine
    command: yarn install
    working_dir: /usr/src/
    volumes:
      - .:/usr/src/:delegated
