# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Gaisa Sargs - Svaigā Gaisa SUPERVARONIS!
email: pasts@gaisasargs.lv
description: >- # this means to ignore newlines until "baseurl:"
  GAISA SARGS ir ir BEZMAKSAS telpu gaisa kvalitātes monitoringa komplekts, kuru var saņemt	organizācijas vai iestādes, kas strādā ar bērniem un jauniešiem. Tā salikšanu veic gala lietotāji.
domain: gaisasargs.lv       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://gaisasargs.lv  # the base hostname and protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme:

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - CNAME

# Social
github_username:  open-lv
relative_permalinks: false

plugins:
  - jekyll-sitemap
